name: Daily CSV Generation and SQL Load

on:
  schedule:
    - cron: '0 0 * * *'   # Runs every day at midnight UTC

jobs:
  data_pipeline:
    runs-on: ubuntu-latest

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pymysql python-dotenv

      - name: Generate consolidated CSV
        run: python scripts/datasource.py

      - name: Shred CSV into table CSVs
        run: python scripts/csv_shredder.py

      - name: Load CSVs into SQL tables
        run: python scripts/csvtosql.py


        